server:
  port: 8887

hystrix.command.fallbackcmd.execution.isolation.thread.timeoutInMilliseconds: 200000
#hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 200000

#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 40000


spring:
  application:
    name: api-gateway-spring

  cloud:
    loadbalancer:
      ribbon:
        enabled: true
    gateway:
      routes:
      - id: servicio-items
        uri: lb://servicio-items
        predicates:
        - Path=/api/items/**
        filters:
        - RewritePath=/api/items/(?<segment>.*), /$\{segment}

      - id: servicio-productos
        uri: lb://servicio-productos
        predicates:
          - Path=/api/productos/**
        filters:
          - RewritePath=/api/productos/(?<segment>.*), /$\{segment}
  zipkin:
    base-url: http://192.168.0.110:9411/

  kafka:
    host: 192.168.0.110

  sleuth:
    sampler:
      probability: 1.0


eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    eureka-server-connect-timeout-seconds: 5
    eureka-service-url-poll-interval-seconds: 5
    registry-fetch-interval-seconds: 2
    initial-instance-info-replication-interval-seconds: 2
    instance-info-replication-interval-seconds: 2
    healthcheck:
      enabled: true
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}-${spring.application.name}
    #status-page-url-path: ${server.servlet.contextPath}${endpoints.info.path:/info}
    #health-check-url-path: ${server.servlet.contextPath}${endpoints.health.path:/health}
    home-page-url-path: ${server.servlet.contextPath}
    lease-expiration-duration-in-seconds: 2
    lease-renewal-interval-in-seconds: 2
    metadata-map:
      instance-id: ${spring.cloud.client.ipAddress}:${server.port}-${spring.application.name}


ribbon:
  eureka:
    enabled: true
  #ConnectTimeout: 45000
  #ReadTimeout: 45000

#management:
#  endpoints:
#    web:
#      exposure:
#        include: hystrix.stream

