version: "3"
services:
  rabbitmq:
    image: rabbitmq:3.7.6-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - "TZ=@timezone@"
    networks:
      - local

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    depends_on:
      - rabbitmq
    ports:
      - "9411:9411"
    environment:
      - "RABBIT_ADDRESSES=guest:guest@rabbitmq:5672"
      - "RABBIT_URI=amqp://guest:guest@rabbitmq:5672"
      - "STORAGE_TYPE=mysql"
      - "MYSQL_USER=testUser"
      - "MYSQL_PASS=testMysql"
      - "TZ=@timezone@"
      - "MYSQL_HOST:192.168.0.110"
    networks:
      - local

networks:
  local: